#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 132
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 62
#define ALIAS_COUNT 0
#define TOKEN_COUNT 35
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define PRODUCTION_ID_COUNT 2

enum {
  anon_sym_func = 1,
  anon_sym_COLON = 2,
  anon_sym_end = 3,
  anon_sym_LPAREN = 4,
  anon_sym_RPAREN = 5,
  anon_sym_COMMA = 6,
  anon_sym_var = 7,
  anon_sym_SEMI = 8,
  anon_sym_int = 9,
  anon_sym_real = 10,
  anon_sym_while = 11,
  anon_sym_do = 12,
  anon_sym_if = 13,
  anon_sym_then = 14,
  anon_sym_else = 15,
  sym_identifier = 16,
  anon_sym_return = 17,
  sym_number = 18,
  anon_sym_as = 19,
  anon_sym_GT = 20,
  anon_sym_LT = 21,
  anon_sym_GT_EQ = 22,
  anon_sym_LT_EQ = 23,
  anon_sym_EQ_EQ = 24,
  anon_sym_BANG_EQ = 25,
  anon_sym_and = 26,
  anon_sym_or = 27,
  anon_sym_PLUS = 28,
  anon_sym_DASH = 29,
  anon_sym_STAR = 30,
  anon_sym_SLASH = 31,
  anon_sym_LBRACK = 32,
  anon_sym_RBRACK = 33,
  anon_sym_COLON_EQ = 34,
  sym_source_file = 35,
  sym__definition = 36,
  sym_function_definition = 37,
  sym_parameter_list = 38,
  sym_parameters = 39,
  sym_parameter = 40,
  sym_variable_declaration = 41,
  sym_primitive_type = 42,
  sym_array_type = 43,
  sym_block = 44,
  sym_statement = 45,
  sym_while = 46,
  sym_if = 47,
  sym_expression = 48,
  sym__expr = 49,
  sym_return_statement = 50,
  sym_type_cast = 51,
  sym_function_call = 52,
  sym_arguments = 53,
  sym_binary_expression = 54,
  sym_array_access = 55,
  sym__brack_expr = 56,
  sym_assignment = 57,
  aux_sym_source_file_repeat1 = 58,
  aux_sym_array_type_repeat1 = 59,
  aux_sym_block_repeat1 = 60,
  aux_sym_block_repeat2 = 61,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_func] = "func",
  [anon_sym_COLON] = ":",
  [anon_sym_end] = "end",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_COMMA] = ",",
  [anon_sym_var] = "var",
  [anon_sym_SEMI] = ";",
  [anon_sym_int] = "int",
  [anon_sym_real] = "real",
  [anon_sym_while] = "while",
  [anon_sym_do] = "do",
  [anon_sym_if] = "if",
  [anon_sym_then] = "then",
  [anon_sym_else] = "else",
  [sym_identifier] = "identifier",
  [anon_sym_return] = "return",
  [sym_number] = "number",
  [anon_sym_as] = "as",
  [anon_sym_GT] = ">",
  [anon_sym_LT] = "<",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_and] = "and",
  [anon_sym_or] = "or",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_COLON_EQ] = ":=",
  [sym_source_file] = "source_file",
  [sym__definition] = "_definition",
  [sym_function_definition] = "function_definition",
  [sym_parameter_list] = "parameter_list",
  [sym_parameters] = "parameters",
  [sym_parameter] = "parameter",
  [sym_variable_declaration] = "variable_declaration",
  [sym_primitive_type] = "primitive_type",
  [sym_array_type] = "array_type",
  [sym_block] = "block",
  [sym_statement] = "statement",
  [sym_while] = "while",
  [sym_if] = "if",
  [sym_expression] = "expression",
  [sym__expr] = "_expr",
  [sym_return_statement] = "return_statement",
  [sym_type_cast] = "type_cast",
  [sym_function_call] = "function_call",
  [sym_arguments] = "arguments",
  [sym_binary_expression] = "binary_expression",
  [sym_array_access] = "array_access",
  [sym__brack_expr] = "_brack_expr",
  [sym_assignment] = "assignment",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_array_type_repeat1] = "array_type_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
  [aux_sym_block_repeat2] = "block_repeat2",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_func] = anon_sym_func,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_end] = anon_sym_end,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_var] = anon_sym_var,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_int] = anon_sym_int,
  [anon_sym_real] = anon_sym_real,
  [anon_sym_while] = anon_sym_while,
  [anon_sym_do] = anon_sym_do,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_then] = anon_sym_then,
  [anon_sym_else] = anon_sym_else,
  [sym_identifier] = sym_identifier,
  [anon_sym_return] = anon_sym_return,
  [sym_number] = sym_number,
  [anon_sym_as] = anon_sym_as,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_and] = anon_sym_and,
  [anon_sym_or] = anon_sym_or,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_COLON_EQ] = anon_sym_COLON_EQ,
  [sym_source_file] = sym_source_file,
  [sym__definition] = sym__definition,
  [sym_function_definition] = sym_function_definition,
  [sym_parameter_list] = sym_parameter_list,
  [sym_parameters] = sym_parameters,
  [sym_parameter] = sym_parameter,
  [sym_variable_declaration] = sym_variable_declaration,
  [sym_primitive_type] = sym_primitive_type,
  [sym_array_type] = sym_array_type,
  [sym_block] = sym_block,
  [sym_statement] = sym_statement,
  [sym_while] = sym_while,
  [sym_if] = sym_if,
  [sym_expression] = sym_expression,
  [sym__expr] = sym__expr,
  [sym_return_statement] = sym_return_statement,
  [sym_type_cast] = sym_type_cast,
  [sym_function_call] = sym_function_call,
  [sym_arguments] = sym_arguments,
  [sym_binary_expression] = sym_binary_expression,
  [sym_array_access] = sym_array_access,
  [sym__brack_expr] = sym__brack_expr,
  [sym_assignment] = sym_assignment,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_array_type_repeat1] = aux_sym_array_type_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
  [aux_sym_block_repeat2] = aux_sym_block_repeat2,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_func] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_end] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_var] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_int] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_real] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_while] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_do] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_then] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_return] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_as] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_and] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_or] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym_function_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym_parameters] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_primitive_type] = {
    .visible = true,
    .named = true,
  },
  [sym_array_type] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_while] = {
    .visible = true,
    .named = true,
  },
  [sym_if] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym__expr] = {
    .visible = false,
    .named = true,
  },
  [sym_return_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_type_cast] = {
    .visible = true,
    .named = true,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [sym_arguments] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_array_access] = {
    .visible = true,
    .named = true,
  },
  [sym__brack_expr] = {
    .visible = false,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_array_type_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat2] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_left = 1,
  field_operator = 2,
  field_right = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_left] = "left",
  [field_operator] = "operator",
  [field_right] = "right",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_left, 0},
    {field_operator, 1},
    {field_right, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 19,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 21,
  [25] = 22,
  [26] = 26,
  [27] = 27,
  [28] = 26,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 34,
  [38] = 33,
  [39] = 39,
  [40] = 29,
  [41] = 39,
  [42] = 35,
  [43] = 31,
  [44] = 44,
  [45] = 32,
  [46] = 46,
  [47] = 46,
  [48] = 46,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 9,
  [54] = 54,
  [55] = 55,
  [56] = 54,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 52,
  [65] = 51,
  [66] = 63,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 17,
  [71] = 71,
  [72] = 72,
  [73] = 6,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 75,
  [81] = 81,
  [82] = 81,
  [83] = 78,
  [84] = 6,
  [85] = 17,
  [86] = 77,
  [87] = 76,
  [88] = 79,
  [89] = 89,
  [90] = 74,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 94,
  [96] = 91,
  [97] = 89,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 107,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 109,
  [114] = 114,
  [115] = 111,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 109,
  [122] = 116,
  [123] = 123,
  [124] = 124,
  [125] = 119,
  [126] = 117,
  [127] = 127,
  [128] = 128,
  [129] = 124,
  [130] = 130,
  [131] = 120,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(37);
      if (lookahead == '!') ADVANCE(4);
      if (lookahead == '(') ADVANCE(43);
      if (lookahead == ')') ADVANCE(44);
      if (lookahead == '*') ADVANCE(92);
      if (lookahead == '+') ADVANCE(90);
      if (lookahead == ',') ADVANCE(45);
      if (lookahead == '-') ADVANCE(91);
      if (lookahead == '/') ADVANCE(93);
      if (lookahead == ':') ADVANCE(40);
      if (lookahead == ';') ADVANCE(48);
      if (lookahead == '<') ADVANCE(83);
      if (lookahead == '=') ADVANCE(6);
      if (lookahead == '>') ADVANCE(82);
      if (lookahead == '[') ADVANCE(94);
      if (lookahead == ']') ADVANCE(95);
      if (lookahead == 'a') ADVANCE(25);
      if (lookahead == 'd') ADVANCE(29);
      if (lookahead == 'e') ADVANCE(22);
      if (lookahead == 'f') ADVANCE(35);
      if (lookahead == 'i') ADVANCE(18);
      if (lookahead == 'o') ADVANCE(30);
      if (lookahead == 'r') ADVANCE(12);
      if (lookahead == 't') ADVANCE(20);
      if (lookahead == 'v') ADVANCE(8);
      if (lookahead == 'w') ADVANCE(19);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(79);
      END_STATE();
    case 1:
      if (lookahead == '!') ADVANCE(4);
      if (lookahead == '(') ADVANCE(43);
      if (lookahead == ')') ADVANCE(44);
      if (lookahead == '*') ADVANCE(92);
      if (lookahead == '+') ADVANCE(90);
      if (lookahead == ',') ADVANCE(45);
      if (lookahead == '-') ADVANCE(91);
      if (lookahead == '/') ADVANCE(93);
      if (lookahead == ':') ADVANCE(5);
      if (lookahead == ';') ADVANCE(48);
      if (lookahead == '<') ADVANCE(83);
      if (lookahead == '=') ADVANCE(6);
      if (lookahead == '>') ADVANCE(82);
      if (lookahead == '[') ADVANCE(94);
      if (lookahead == ']') ADVANCE(95);
      if (lookahead == 'a') ADVANCE(25);
      if (lookahead == 'd') ADVANCE(29);
      if (lookahead == 'o') ADVANCE(30);
      if (lookahead == 't') ADVANCE(20);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      END_STATE();
    case 2:
      if (lookahead == '(') ADVANCE(43);
      if (lookahead == ')') ADVANCE(44);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(79);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 3:
      if (lookahead == ')') ADVANCE(44);
      if (lookahead == ',') ADVANCE(45);
      if (lookahead == ':') ADVANCE(39);
      if (lookahead == ';') ADVANCE(48);
      if (lookahead == '[') ADVANCE(94);
      if (lookahead == 'i') ADVANCE(64);
      if (lookahead == 'r') ADVANCE(61);
      if (lookahead == 'v') ADVANCE(59);
      if (lookahead == 'w') ADVANCE(65);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(3)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 4:
      if (lookahead == '=') ADVANCE(87);
      END_STATE();
    case 5:
      if (lookahead == '=') ADVANCE(96);
      END_STATE();
    case 6:
      if (lookahead == '=') ADVANCE(86);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(23);
      if (lookahead == 't') ADVANCE(36);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(31);
      END_STATE();
    case 9:
      if (lookahead == 'c') ADVANCE(38);
      END_STATE();
    case 10:
      if (lookahead == 'd') ADVANCE(88);
      END_STATE();
    case 11:
      if (lookahead == 'd') ADVANCE(41);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(7);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(57);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(51);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(67);
      if (lookahead == 'i') ADVANCE(64);
      if (lookahead == 'r') ADVANCE(61);
      if (lookahead == 'w') ADVANCE(65);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(15)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(27);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(70);
      if (lookahead == 'i') ADVANCE(64);
      if (lookahead == 'r') ADVANCE(61);
      if (lookahead == 'w') ADVANCE(65);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(17)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 18:
      if (lookahead == 'f') ADVANCE(54);
      if (lookahead == 'n') ADVANCE(34);
      END_STATE();
    case 19:
      if (lookahead == 'h') ADVANCE(21);
      END_STATE();
    case 20:
      if (lookahead == 'h') ADVANCE(16);
      END_STATE();
    case 21:
      if (lookahead == 'i') ADVANCE(24);
      END_STATE();
    case 22:
      if (lookahead == 'l') ADVANCE(33);
      if (lookahead == 'n') ADVANCE(11);
      END_STATE();
    case 23:
      if (lookahead == 'l') ADVANCE(50);
      END_STATE();
    case 24:
      if (lookahead == 'l') ADVANCE(14);
      END_STATE();
    case 25:
      if (lookahead == 'n') ADVANCE(10);
      if (lookahead == 's') ADVANCE(81);
      END_STATE();
    case 26:
      if (lookahead == 'n') ADVANCE(9);
      END_STATE();
    case 27:
      if (lookahead == 'n') ADVANCE(56);
      END_STATE();
    case 28:
      if (lookahead == 'n') ADVANCE(77);
      END_STATE();
    case 29:
      if (lookahead == 'o') ADVANCE(53);
      END_STATE();
    case 30:
      if (lookahead == 'r') ADVANCE(89);
      END_STATE();
    case 31:
      if (lookahead == 'r') ADVANCE(46);
      END_STATE();
    case 32:
      if (lookahead == 'r') ADVANCE(28);
      END_STATE();
    case 33:
      if (lookahead == 's') ADVANCE(13);
      END_STATE();
    case 34:
      if (lookahead == 't') ADVANCE(49);
      END_STATE();
    case 35:
      if (lookahead == 'u') ADVANCE(26);
      END_STATE();
    case 36:
      if (lookahead == 'u') ADVANCE(32);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_func);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == '=') ADVANCE(96);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_end);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_end);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_var);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_var);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_int);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_real);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_while);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_while);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_do);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_if);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_then);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_else);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(71);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(74);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(58);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'f') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'h') ADVANCE(66);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(68);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(73);
      if (lookahead == 'n') ADVANCE(60);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(62);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(78);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(60);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(47);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(69);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(63);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(75);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(72);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_return);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_return);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(80);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(79);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(80);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_as);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(84);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(85);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_and);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_or);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(anon_sym_COLON_EQ);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 3},
  [19] = {.lex_state = 3},
  [20] = {.lex_state = 3},
  [21] = {.lex_state = 3},
  [22] = {.lex_state = 3},
  [23] = {.lex_state = 3},
  [24] = {.lex_state = 3},
  [25] = {.lex_state = 3},
  [26] = {.lex_state = 3},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 3},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 15},
  [32] = {.lex_state = 15},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 15},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 17},
  [43] = {.lex_state = 17},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 17},
  [46] = {.lex_state = 2},
  [47] = {.lex_state = 2},
  [48] = {.lex_state = 2},
  [49] = {.lex_state = 2},
  [50] = {.lex_state = 2},
  [51] = {.lex_state = 2},
  [52] = {.lex_state = 2},
  [53] = {.lex_state = 3},
  [54] = {.lex_state = 2},
  [55] = {.lex_state = 2},
  [56] = {.lex_state = 2},
  [57] = {.lex_state = 2},
  [58] = {.lex_state = 2},
  [59] = {.lex_state = 2},
  [60] = {.lex_state = 2},
  [61] = {.lex_state = 2},
  [62] = {.lex_state = 2},
  [63] = {.lex_state = 2},
  [64] = {.lex_state = 2},
  [65] = {.lex_state = 2},
  [66] = {.lex_state = 2},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 3},
  [70] = {.lex_state = 15},
  [71] = {.lex_state = 3},
  [72] = {.lex_state = 3},
  [73] = {.lex_state = 15},
  [74] = {.lex_state = 15},
  [75] = {.lex_state = 15},
  [76] = {.lex_state = 15},
  [77] = {.lex_state = 15},
  [78] = {.lex_state = 15},
  [79] = {.lex_state = 15},
  [80] = {.lex_state = 17},
  [81] = {.lex_state = 1},
  [82] = {.lex_state = 1},
  [83] = {.lex_state = 17},
  [84] = {.lex_state = 17},
  [85] = {.lex_state = 17},
  [86] = {.lex_state = 17},
  [87] = {.lex_state = 17},
  [88] = {.lex_state = 17},
  [89] = {.lex_state = 3},
  [90] = {.lex_state = 17},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 2},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 2},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 2},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 1},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 3},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 2},
  [125] = {.lex_state = 3},
  [126] = {.lex_state = 1},
  [127] = {.lex_state = 0},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 2},
  [130] = {.lex_state = 3},
  [131] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_func] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_end] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_var] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_int] = ACTIONS(1),
    [anon_sym_real] = ACTIONS(1),
    [anon_sym_while] = ACTIONS(1),
    [anon_sym_do] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_then] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_return] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_as] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_and] = ACTIONS(1),
    [anon_sym_or] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_COLON_EQ] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(123),
    [sym__definition] = STATE(68),
    [sym_function_definition] = STATE(68),
    [sym_variable_declaration] = STATE(68),
    [aux_sym_source_file_repeat1] = STATE(68),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_func] = ACTIONS(5),
    [anon_sym_var] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 2,
      anon_sym_GT,
      anon_sym_LT,
    STATE(3), 2,
      sym__brack_expr,
      aux_sym_array_type_repeat1,
    ACTIONS(11), 17,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_do,
      anon_sym_then,
      anon_sym_as,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_and,
      anon_sym_or,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_RBRACK,
  [34] = 4,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 2,
      anon_sym_GT,
      anon_sym_LT,
    STATE(4), 2,
      sym__brack_expr,
      aux_sym_array_type_repeat1,
    ACTIONS(17), 18,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_do,
      anon_sym_then,
      anon_sym_as,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_and,
      anon_sym_or,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_RBRACK,
      anon_sym_COLON_EQ,
  [66] = 4,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 2,
      anon_sym_GT,
      anon_sym_LT,
    STATE(4), 2,
      sym__brack_expr,
      aux_sym_array_type_repeat1,
    ACTIONS(21), 18,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_do,
      anon_sym_then,
      anon_sym_as,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_and,
      anon_sym_or,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_RBRACK,
      anon_sym_COLON_EQ,
  [98] = 2,
    ACTIONS(30), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(28), 19,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_do,
      anon_sym_then,
      anon_sym_as,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_and,
      anon_sym_or,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COLON_EQ,
  [124] = 2,
    ACTIONS(34), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(32), 17,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_do,
      anon_sym_then,
      anon_sym_as,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_and,
      anon_sym_or,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_RBRACK,
  [148] = 4,
    ACTIONS(38), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(40), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(42), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(36), 13,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_do,
      anon_sym_then,
      anon_sym_as,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_and,
      anon_sym_or,
      anon_sym_RBRACK,
  [176] = 2,
    ACTIONS(46), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(44), 17,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_do,
      anon_sym_then,
      anon_sym_as,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_and,
      anon_sym_or,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_RBRACK,
  [200] = 2,
    ACTIONS(50), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(48), 17,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_do,
      anon_sym_then,
      anon_sym_as,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_and,
      anon_sym_or,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_RBRACK,
  [224] = 2,
    ACTIONS(54), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(52), 17,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_do,
      anon_sym_then,
      anon_sym_as,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_and,
      anon_sym_or,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_RBRACK,
  [248] = 2,
    ACTIONS(58), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(56), 17,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_do,
      anon_sym_then,
      anon_sym_as,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_and,
      anon_sym_or,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_RBRACK,
  [272] = 2,
    ACTIONS(38), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(36), 17,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_do,
      anon_sym_then,
      anon_sym_as,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_and,
      anon_sym_or,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_RBRACK,
  [296] = 3,
    ACTIONS(38), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(42), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(36), 15,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_do,
      anon_sym_then,
      anon_sym_as,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_and,
      anon_sym_or,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_RBRACK,
  [322] = 7,
    ACTIONS(66), 1,
      anon_sym_and,
    ACTIONS(40), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(42), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(60), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(62), 2,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    ACTIONS(64), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(36), 8,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_do,
      anon_sym_then,
      anon_sym_as,
      anon_sym_or,
      anon_sym_RBRACK,
  [356] = 6,
    ACTIONS(40), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(42), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(60), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(62), 2,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    ACTIONS(64), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(36), 9,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_do,
      anon_sym_then,
      anon_sym_as,
      anon_sym_and,
      anon_sym_or,
      anon_sym_RBRACK,
  [388] = 5,
    ACTIONS(40), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(42), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(60), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(62), 2,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    ACTIONS(36), 11,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_do,
      anon_sym_then,
      anon_sym_as,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_and,
      anon_sym_or,
      anon_sym_RBRACK,
  [418] = 2,
    ACTIONS(70), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(68), 17,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_do,
      anon_sym_then,
      anon_sym_as,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_and,
      anon_sym_or,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_RBRACK,
  [442] = 11,
    ACTIONS(72), 1,
      anon_sym_COLON,
    ACTIONS(74), 1,
      anon_sym_var,
    ACTIONS(76), 1,
      anon_sym_while,
    ACTIONS(78), 1,
      anon_sym_if,
    ACTIONS(80), 1,
      sym_identifier,
    ACTIONS(82), 1,
      anon_sym_return,
    STATE(117), 1,
      sym_array_access,
    STATE(118), 1,
      sym_block,
    STATE(28), 2,
      sym_variable_declaration,
      aux_sym_block_repeat1,
    STATE(43), 2,
      sym_statement,
      aux_sym_block_repeat2,
    STATE(88), 5,
      sym_while,
      sym_if,
      sym_return_statement,
      sym_function_call,
      sym_assignment,
  [482] = 10,
    ACTIONS(74), 1,
      anon_sym_var,
    ACTIONS(76), 1,
      anon_sym_while,
    ACTIONS(78), 1,
      anon_sym_if,
    ACTIONS(80), 1,
      sym_identifier,
    ACTIONS(82), 1,
      anon_sym_return,
    STATE(117), 1,
      sym_array_access,
    STATE(122), 1,
      sym_block,
    STATE(28), 2,
      sym_variable_declaration,
      aux_sym_block_repeat1,
    STATE(43), 2,
      sym_statement,
      aux_sym_block_repeat2,
    STATE(88), 5,
      sym_while,
      sym_if,
      sym_return_statement,
      sym_function_call,
      sym_assignment,
  [519] = 10,
    ACTIONS(74), 1,
      anon_sym_var,
    ACTIONS(76), 1,
      anon_sym_while,
    ACTIONS(78), 1,
      anon_sym_if,
    ACTIONS(80), 1,
      sym_identifier,
    ACTIONS(82), 1,
      anon_sym_return,
    STATE(116), 1,
      sym_block,
    STATE(117), 1,
      sym_array_access,
    STATE(28), 2,
      sym_variable_declaration,
      aux_sym_block_repeat1,
    STATE(43), 2,
      sym_statement,
      aux_sym_block_repeat2,
    STATE(88), 5,
      sym_while,
      sym_if,
      sym_return_statement,
      sym_function_call,
      sym_assignment,
  [556] = 10,
    ACTIONS(74), 1,
      anon_sym_var,
    ACTIONS(76), 1,
      anon_sym_while,
    ACTIONS(78), 1,
      anon_sym_if,
    ACTIONS(80), 1,
      sym_identifier,
    ACTIONS(82), 1,
      anon_sym_return,
    STATE(111), 1,
      sym_block,
    STATE(117), 1,
      sym_array_access,
    STATE(28), 2,
      sym_variable_declaration,
      aux_sym_block_repeat1,
    STATE(43), 2,
      sym_statement,
      aux_sym_block_repeat2,
    STATE(88), 5,
      sym_while,
      sym_if,
      sym_return_statement,
      sym_function_call,
      sym_assignment,
  [593] = 10,
    ACTIONS(74), 1,
      anon_sym_var,
    ACTIONS(84), 1,
      anon_sym_while,
    ACTIONS(86), 1,
      anon_sym_if,
    ACTIONS(88), 1,
      sym_identifier,
    ACTIONS(90), 1,
      anon_sym_return,
    STATE(107), 1,
      sym_block,
    STATE(126), 1,
      sym_array_access,
    STATE(26), 2,
      sym_variable_declaration,
      aux_sym_block_repeat1,
    STATE(31), 2,
      sym_statement,
      aux_sym_block_repeat2,
    STATE(79), 5,
      sym_while,
      sym_if,
      sym_return_statement,
      sym_function_call,
      sym_assignment,
  [630] = 10,
    ACTIONS(74), 1,
      anon_sym_var,
    ACTIONS(76), 1,
      anon_sym_while,
    ACTIONS(78), 1,
      anon_sym_if,
    ACTIONS(80), 1,
      sym_identifier,
    ACTIONS(82), 1,
      anon_sym_return,
    STATE(112), 1,
      sym_block,
    STATE(117), 1,
      sym_array_access,
    STATE(28), 2,
      sym_variable_declaration,
      aux_sym_block_repeat1,
    STATE(43), 2,
      sym_statement,
      aux_sym_block_repeat2,
    STATE(88), 5,
      sym_while,
      sym_if,
      sym_return_statement,
      sym_function_call,
      sym_assignment,
  [667] = 10,
    ACTIONS(74), 1,
      anon_sym_var,
    ACTIONS(76), 1,
      anon_sym_while,
    ACTIONS(78), 1,
      anon_sym_if,
    ACTIONS(80), 1,
      sym_identifier,
    ACTIONS(82), 1,
      anon_sym_return,
    STATE(115), 1,
      sym_block,
    STATE(117), 1,
      sym_array_access,
    STATE(28), 2,
      sym_variable_declaration,
      aux_sym_block_repeat1,
    STATE(43), 2,
      sym_statement,
      aux_sym_block_repeat2,
    STATE(88), 5,
      sym_while,
      sym_if,
      sym_return_statement,
      sym_function_call,
      sym_assignment,
  [704] = 10,
    ACTIONS(74), 1,
      anon_sym_var,
    ACTIONS(84), 1,
      anon_sym_while,
    ACTIONS(86), 1,
      anon_sym_if,
    ACTIONS(88), 1,
      sym_identifier,
    ACTIONS(90), 1,
      anon_sym_return,
    STATE(108), 1,
      sym_block,
    STATE(126), 1,
      sym_array_access,
    STATE(26), 2,
      sym_variable_declaration,
      aux_sym_block_repeat1,
    STATE(31), 2,
      sym_statement,
      aux_sym_block_repeat2,
    STATE(79), 5,
      sym_while,
      sym_if,
      sym_return_statement,
      sym_function_call,
      sym_assignment,
  [741] = 9,
    ACTIONS(74), 1,
      anon_sym_var,
    ACTIONS(84), 1,
      anon_sym_while,
    ACTIONS(86), 1,
      anon_sym_if,
    ACTIONS(88), 1,
      sym_identifier,
    ACTIONS(90), 1,
      anon_sym_return,
    STATE(126), 1,
      sym_array_access,
    STATE(32), 2,
      sym_statement,
      aux_sym_block_repeat2,
    STATE(69), 2,
      sym_variable_declaration,
      aux_sym_block_repeat1,
    STATE(79), 5,
      sym_while,
      sym_if,
      sym_return_statement,
      sym_function_call,
      sym_assignment,
  [775] = 10,
    ACTIONS(66), 1,
      anon_sym_and,
    ACTIONS(92), 1,
      anon_sym_RPAREN,
    ACTIONS(94), 1,
      anon_sym_COMMA,
    ACTIONS(96), 1,
      anon_sym_as,
    ACTIONS(98), 1,
      anon_sym_or,
    ACTIONS(40), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(42), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(60), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(62), 2,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    ACTIONS(64), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [811] = 9,
    ACTIONS(74), 1,
      anon_sym_var,
    ACTIONS(76), 1,
      anon_sym_while,
    ACTIONS(78), 1,
      anon_sym_if,
    ACTIONS(80), 1,
      sym_identifier,
    ACTIONS(82), 1,
      anon_sym_return,
    STATE(117), 1,
      sym_array_access,
    STATE(45), 2,
      sym_statement,
      aux_sym_block_repeat2,
    STATE(69), 2,
      sym_variable_declaration,
      aux_sym_block_repeat1,
    STATE(88), 5,
      sym_while,
      sym_if,
      sym_return_statement,
      sym_function_call,
      sym_assignment,
  [845] = 9,
    ACTIONS(66), 1,
      anon_sym_and,
    ACTIONS(96), 1,
      anon_sym_as,
    ACTIONS(98), 1,
      anon_sym_or,
    ACTIONS(100), 1,
      anon_sym_SEMI,
    ACTIONS(40), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(42), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(60), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(62), 2,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    ACTIONS(64), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [878] = 9,
    ACTIONS(66), 1,
      anon_sym_and,
    ACTIONS(96), 1,
      anon_sym_as,
    ACTIONS(98), 1,
      anon_sym_or,
    ACTIONS(102), 1,
      anon_sym_RBRACK,
    ACTIONS(40), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(42), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(60), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(62), 2,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    ACTIONS(64), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [911] = 8,
    ACTIONS(84), 1,
      anon_sym_while,
    ACTIONS(86), 1,
      anon_sym_if,
    ACTIONS(88), 1,
      sym_identifier,
    ACTIONS(90), 1,
      anon_sym_return,
    STATE(126), 1,
      sym_array_access,
    ACTIONS(104), 2,
      anon_sym_end,
      anon_sym_else,
    STATE(35), 2,
      sym_statement,
      aux_sym_block_repeat2,
    STATE(79), 5,
      sym_while,
      sym_if,
      sym_return_statement,
      sym_function_call,
      sym_assignment,
  [942] = 8,
    ACTIONS(84), 1,
      anon_sym_while,
    ACTIONS(86), 1,
      anon_sym_if,
    ACTIONS(88), 1,
      sym_identifier,
    ACTIONS(90), 1,
      anon_sym_return,
    STATE(126), 1,
      sym_array_access,
    ACTIONS(106), 2,
      anon_sym_end,
      anon_sym_else,
    STATE(35), 2,
      sym_statement,
      aux_sym_block_repeat2,
    STATE(79), 5,
      sym_while,
      sym_if,
      sym_return_statement,
      sym_function_call,
      sym_assignment,
  [973] = 9,
    ACTIONS(66), 1,
      anon_sym_and,
    ACTIONS(96), 1,
      anon_sym_as,
    ACTIONS(98), 1,
      anon_sym_or,
    ACTIONS(108), 1,
      anon_sym_then,
    ACTIONS(40), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(42), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(60), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(62), 2,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    ACTIONS(64), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [1006] = 9,
    ACTIONS(66), 1,
      anon_sym_and,
    ACTIONS(96), 1,
      anon_sym_as,
    ACTIONS(98), 1,
      anon_sym_or,
    ACTIONS(110), 1,
      anon_sym_do,
    ACTIONS(40), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(42), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(60), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(62), 2,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    ACTIONS(64), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [1039] = 8,
    ACTIONS(114), 1,
      anon_sym_while,
    ACTIONS(117), 1,
      anon_sym_if,
    ACTIONS(120), 1,
      sym_identifier,
    ACTIONS(123), 1,
      anon_sym_return,
    STATE(126), 1,
      sym_array_access,
    ACTIONS(112), 2,
      anon_sym_end,
      anon_sym_else,
    STATE(35), 2,
      sym_statement,
      aux_sym_block_repeat2,
    STATE(79), 5,
      sym_while,
      sym_if,
      sym_return_statement,
      sym_function_call,
      sym_assignment,
  [1070] = 3,
    ACTIONS(126), 1,
      anon_sym_RPAREN,
    ACTIONS(46), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(44), 11,
      anon_sym_as,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_and,
      anon_sym_or,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1091] = 9,
    ACTIONS(66), 1,
      anon_sym_and,
    ACTIONS(96), 1,
      anon_sym_as,
    ACTIONS(98), 1,
      anon_sym_or,
    ACTIONS(128), 1,
      anon_sym_do,
    ACTIONS(40), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(42), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(60), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(62), 2,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    ACTIONS(64), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [1124] = 9,
    ACTIONS(66), 1,
      anon_sym_and,
    ACTIONS(96), 1,
      anon_sym_as,
    ACTIONS(98), 1,
      anon_sym_or,
    ACTIONS(130), 1,
      anon_sym_then,
    ACTIONS(40), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(42), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(60), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(62), 2,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    ACTIONS(64), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [1157] = 9,
    ACTIONS(66), 1,
      anon_sym_and,
    ACTIONS(96), 1,
      anon_sym_as,
    ACTIONS(98), 1,
      anon_sym_or,
    ACTIONS(132), 1,
      anon_sym_SEMI,
    ACTIONS(40), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(42), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(60), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(62), 2,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    ACTIONS(64), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [1190] = 9,
    ACTIONS(66), 1,
      anon_sym_and,
    ACTIONS(96), 1,
      anon_sym_as,
    ACTIONS(98), 1,
      anon_sym_or,
    ACTIONS(134), 1,
      anon_sym_SEMI,
    ACTIONS(40), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(42), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(60), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(62), 2,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    ACTIONS(64), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [1223] = 9,
    ACTIONS(66), 1,
      anon_sym_and,
    ACTIONS(96), 1,
      anon_sym_as,
    ACTIONS(98), 1,
      anon_sym_or,
    ACTIONS(136), 1,
      anon_sym_SEMI,
    ACTIONS(40), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(42), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(60), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(62), 2,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    ACTIONS(64), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [1256] = 8,
    ACTIONS(112), 1,
      anon_sym_end,
    ACTIONS(138), 1,
      anon_sym_while,
    ACTIONS(141), 1,
      anon_sym_if,
    ACTIONS(144), 1,
      sym_identifier,
    ACTIONS(147), 1,
      anon_sym_return,
    STATE(117), 1,
      sym_array_access,
    STATE(42), 2,
      sym_statement,
      aux_sym_block_repeat2,
    STATE(88), 5,
      sym_while,
      sym_if,
      sym_return_statement,
      sym_function_call,
      sym_assignment,
  [1286] = 8,
    ACTIONS(76), 1,
      anon_sym_while,
    ACTIONS(78), 1,
      anon_sym_if,
    ACTIONS(80), 1,
      sym_identifier,
    ACTIONS(82), 1,
      anon_sym_return,
    ACTIONS(104), 1,
      anon_sym_end,
    STATE(117), 1,
      sym_array_access,
    STATE(42), 2,
      sym_statement,
      aux_sym_block_repeat2,
    STATE(88), 5,
      sym_while,
      sym_if,
      sym_return_statement,
      sym_function_call,
      sym_assignment,
  [1316] = 8,
    ACTIONS(66), 1,
      anon_sym_and,
    ACTIONS(96), 1,
      anon_sym_as,
    ACTIONS(98), 1,
      anon_sym_or,
    ACTIONS(40), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(42), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(60), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(62), 2,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    ACTIONS(64), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [1346] = 8,
    ACTIONS(76), 1,
      anon_sym_while,
    ACTIONS(78), 1,
      anon_sym_if,
    ACTIONS(80), 1,
      sym_identifier,
    ACTIONS(82), 1,
      anon_sym_return,
    ACTIONS(106), 1,
      anon_sym_end,
    STATE(117), 1,
      sym_array_access,
    STATE(42), 2,
      sym_statement,
      aux_sym_block_repeat2,
    STATE(88), 5,
      sym_while,
      sym_if,
      sym_return_statement,
      sym_function_call,
      sym_assignment,
  [1376] = 7,
    ACTIONS(150), 1,
      anon_sym_LPAREN,
    ACTIONS(152), 1,
      anon_sym_RPAREN,
    ACTIONS(154), 1,
      sym_identifier,
    ACTIONS(156), 1,
      sym_number,
    STATE(27), 1,
      sym_expression,
    STATE(109), 1,
      sym_arguments,
    STATE(8), 5,
      sym__expr,
      sym_type_cast,
      sym_function_call,
      sym_binary_expression,
      sym_array_access,
  [1402] = 7,
    ACTIONS(150), 1,
      anon_sym_LPAREN,
    ACTIONS(154), 1,
      sym_identifier,
    ACTIONS(156), 1,
      sym_number,
    ACTIONS(158), 1,
      anon_sym_RPAREN,
    STATE(27), 1,
      sym_expression,
    STATE(121), 1,
      sym_arguments,
    STATE(8), 5,
      sym__expr,
      sym_type_cast,
      sym_function_call,
      sym_binary_expression,
      sym_array_access,
  [1428] = 7,
    ACTIONS(150), 1,
      anon_sym_LPAREN,
    ACTIONS(154), 1,
      sym_identifier,
    ACTIONS(156), 1,
      sym_number,
    ACTIONS(160), 1,
      anon_sym_RPAREN,
    STATE(27), 1,
      sym_expression,
    STATE(113), 1,
      sym_arguments,
    STATE(8), 5,
      sym__expr,
      sym_type_cast,
      sym_function_call,
      sym_binary_expression,
      sym_array_access,
  [1454] = 6,
    ACTIONS(150), 1,
      anon_sym_LPAREN,
    ACTIONS(154), 1,
      sym_identifier,
    ACTIONS(156), 1,
      sym_number,
    STATE(27), 1,
      sym_expression,
    STATE(127), 1,
      sym_arguments,
    STATE(8), 5,
      sym__expr,
      sym_type_cast,
      sym_function_call,
      sym_binary_expression,
      sym_array_access,
  [1477] = 5,
    ACTIONS(150), 1,
      anon_sym_LPAREN,
    ACTIONS(154), 1,
      sym_identifier,
    ACTIONS(156), 1,
      sym_number,
    STATE(7), 1,
      sym_expression,
    STATE(8), 5,
      sym__expr,
      sym_type_cast,
      sym_function_call,
      sym_binary_expression,
      sym_array_access,
  [1497] = 5,
    ACTIONS(150), 1,
      anon_sym_LPAREN,
    ACTIONS(154), 1,
      sym_identifier,
    ACTIONS(156), 1,
      sym_number,
    STATE(39), 1,
      sym_expression,
    STATE(8), 5,
      sym__expr,
      sym_type_cast,
      sym_function_call,
      sym_binary_expression,
      sym_array_access,
  [1517] = 5,
    ACTIONS(150), 1,
      anon_sym_LPAREN,
    ACTIONS(154), 1,
      sym_identifier,
    ACTIONS(156), 1,
      sym_number,
    STATE(38), 1,
      sym_expression,
    STATE(8), 5,
      sym__expr,
      sym_type_cast,
      sym_function_call,
      sym_binary_expression,
      sym_array_access,
  [1537] = 2,
    ACTIONS(48), 4,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_LBRACK,
    ACTIONS(50), 5,
      anon_sym_var,
      anon_sym_while,
      anon_sym_if,
      sym_identifier,
      anon_sym_return,
  [1551] = 5,
    ACTIONS(150), 1,
      anon_sym_LPAREN,
    ACTIONS(154), 1,
      sym_identifier,
    ACTIONS(156), 1,
      sym_number,
    STATE(29), 1,
      sym_expression,
    STATE(8), 5,
      sym__expr,
      sym_type_cast,
      sym_function_call,
      sym_binary_expression,
      sym_array_access,
  [1571] = 5,
    ACTIONS(150), 1,
      anon_sym_LPAREN,
    ACTIONS(154), 1,
      sym_identifier,
    ACTIONS(156), 1,
      sym_number,
    STATE(30), 1,
      sym_expression,
    STATE(8), 5,
      sym__expr,
      sym_type_cast,
      sym_function_call,
      sym_binary_expression,
      sym_array_access,
  [1591] = 5,
    ACTIONS(150), 1,
      anon_sym_LPAREN,
    ACTIONS(154), 1,
      sym_identifier,
    ACTIONS(156), 1,
      sym_number,
    STATE(40), 1,
      sym_expression,
    STATE(8), 5,
      sym__expr,
      sym_type_cast,
      sym_function_call,
      sym_binary_expression,
      sym_array_access,
  [1611] = 5,
    ACTIONS(150), 1,
      anon_sym_LPAREN,
    ACTIONS(154), 1,
      sym_identifier,
    ACTIONS(156), 1,
      sym_number,
    STATE(16), 1,
      sym_expression,
    STATE(8), 5,
      sym__expr,
      sym_type_cast,
      sym_function_call,
      sym_binary_expression,
      sym_array_access,
  [1631] = 5,
    ACTIONS(150), 1,
      anon_sym_LPAREN,
    ACTIONS(154), 1,
      sym_identifier,
    ACTIONS(156), 1,
      sym_number,
    STATE(15), 1,
      sym_expression,
    STATE(8), 5,
      sym__expr,
      sym_type_cast,
      sym_function_call,
      sym_binary_expression,
      sym_array_access,
  [1651] = 5,
    ACTIONS(150), 1,
      anon_sym_LPAREN,
    ACTIONS(154), 1,
      sym_identifier,
    ACTIONS(156), 1,
      sym_number,
    STATE(14), 1,
      sym_expression,
    STATE(8), 5,
      sym__expr,
      sym_type_cast,
      sym_function_call,
      sym_binary_expression,
      sym_array_access,
  [1671] = 5,
    ACTIONS(150), 1,
      anon_sym_LPAREN,
    ACTIONS(154), 1,
      sym_identifier,
    ACTIONS(156), 1,
      sym_number,
    STATE(13), 1,
      sym_expression,
    STATE(8), 5,
      sym__expr,
      sym_type_cast,
      sym_function_call,
      sym_binary_expression,
      sym_array_access,
  [1691] = 5,
    ACTIONS(150), 1,
      anon_sym_LPAREN,
    ACTIONS(154), 1,
      sym_identifier,
    ACTIONS(156), 1,
      sym_number,
    STATE(12), 1,
      sym_expression,
    STATE(8), 5,
      sym__expr,
      sym_type_cast,
      sym_function_call,
      sym_binary_expression,
      sym_array_access,
  [1711] = 5,
    ACTIONS(150), 1,
      anon_sym_LPAREN,
    ACTIONS(154), 1,
      sym_identifier,
    ACTIONS(162), 1,
      sym_number,
    STATE(44), 1,
      sym_expression,
    STATE(36), 5,
      sym__expr,
      sym_type_cast,
      sym_function_call,
      sym_binary_expression,
      sym_array_access,
  [1731] = 5,
    ACTIONS(150), 1,
      anon_sym_LPAREN,
    ACTIONS(154), 1,
      sym_identifier,
    ACTIONS(156), 1,
      sym_number,
    STATE(34), 1,
      sym_expression,
    STATE(8), 5,
      sym__expr,
      sym_type_cast,
      sym_function_call,
      sym_binary_expression,
      sym_array_access,
  [1751] = 5,
    ACTIONS(150), 1,
      anon_sym_LPAREN,
    ACTIONS(154), 1,
      sym_identifier,
    ACTIONS(156), 1,
      sym_number,
    STATE(33), 1,
      sym_expression,
    STATE(8), 5,
      sym__expr,
      sym_type_cast,
      sym_function_call,
      sym_binary_expression,
      sym_array_access,
  [1771] = 5,
    ACTIONS(150), 1,
      anon_sym_LPAREN,
    ACTIONS(154), 1,
      sym_identifier,
    ACTIONS(156), 1,
      sym_number,
    STATE(41), 1,
      sym_expression,
    STATE(8), 5,
      sym__expr,
      sym_type_cast,
      sym_function_call,
      sym_binary_expression,
      sym_array_access,
  [1791] = 5,
    ACTIONS(150), 1,
      anon_sym_LPAREN,
    ACTIONS(154), 1,
      sym_identifier,
    ACTIONS(156), 1,
      sym_number,
    STATE(37), 1,
      sym_expression,
    STATE(8), 5,
      sym__expr,
      sym_type_cast,
      sym_function_call,
      sym_binary_expression,
      sym_array_access,
  [1811] = 4,
    ACTIONS(164), 1,
      ts_builtin_sym_end,
    ACTIONS(166), 1,
      anon_sym_func,
    ACTIONS(169), 1,
      anon_sym_var,
    STATE(67), 4,
      sym__definition,
      sym_function_definition,
      sym_variable_declaration,
      aux_sym_source_file_repeat1,
  [1827] = 4,
    ACTIONS(5), 1,
      anon_sym_func,
    ACTIONS(7), 1,
      anon_sym_var,
    ACTIONS(172), 1,
      ts_builtin_sym_end,
    STATE(67), 4,
      sym__definition,
      sym_function_definition,
      sym_variable_declaration,
      aux_sym_source_file_repeat1,
  [1843] = 3,
    ACTIONS(174), 1,
      anon_sym_var,
    STATE(69), 2,
      sym_variable_declaration,
      aux_sym_block_repeat1,
    ACTIONS(177), 4,
      anon_sym_while,
      anon_sym_if,
      sym_identifier,
      anon_sym_return,
  [1857] = 1,
    ACTIONS(70), 6,
      anon_sym_end,
      anon_sym_while,
      anon_sym_if,
      anon_sym_else,
      sym_identifier,
      anon_sym_return,
  [1866] = 2,
    ACTIONS(179), 1,
      anon_sym_COLON,
    ACTIONS(181), 5,
      anon_sym_var,
      anon_sym_while,
      anon_sym_if,
      sym_identifier,
      anon_sym_return,
  [1877] = 2,
    ACTIONS(183), 1,
      anon_sym_COLON,
    ACTIONS(185), 5,
      anon_sym_var,
      anon_sym_while,
      anon_sym_if,
      sym_identifier,
      anon_sym_return,
  [1888] = 1,
    ACTIONS(34), 6,
      anon_sym_end,
      anon_sym_while,
      anon_sym_if,
      anon_sym_else,
      sym_identifier,
      anon_sym_return,
  [1897] = 1,
    ACTIONS(187), 6,
      anon_sym_end,
      anon_sym_while,
      anon_sym_if,
      anon_sym_else,
      sym_identifier,
      anon_sym_return,
  [1906] = 1,
    ACTIONS(189), 6,
      anon_sym_end,
      anon_sym_while,
      anon_sym_if,
      anon_sym_else,
      sym_identifier,
      anon_sym_return,
  [1915] = 1,
    ACTIONS(191), 6,
      anon_sym_end,
      anon_sym_while,
      anon_sym_if,
      anon_sym_else,
      sym_identifier,
      anon_sym_return,
  [1924] = 1,
    ACTIONS(193), 6,
      anon_sym_end,
      anon_sym_while,
      anon_sym_if,
      anon_sym_else,
      sym_identifier,
      anon_sym_return,
  [1933] = 1,
    ACTIONS(195), 6,
      anon_sym_end,
      anon_sym_while,
      anon_sym_if,
      anon_sym_else,
      sym_identifier,
      anon_sym_return,
  [1942] = 1,
    ACTIONS(197), 6,
      anon_sym_end,
      anon_sym_while,
      anon_sym_if,
      anon_sym_else,
      sym_identifier,
      anon_sym_return,
  [1951] = 1,
    ACTIONS(189), 5,
      anon_sym_end,
      anon_sym_while,
      anon_sym_if,
      sym_identifier,
      anon_sym_return,
  [1959] = 4,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(199), 1,
      anon_sym_LPAREN,
    ACTIONS(201), 1,
      anon_sym_COLON_EQ,
    STATE(3), 2,
      sym__brack_expr,
      aux_sym_array_type_repeat1,
  [1973] = 4,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(203), 1,
      anon_sym_LPAREN,
    ACTIONS(205), 1,
      anon_sym_COLON_EQ,
    STATE(3), 2,
      sym__brack_expr,
      aux_sym_array_type_repeat1,
  [1987] = 1,
    ACTIONS(195), 5,
      anon_sym_end,
      anon_sym_while,
      anon_sym_if,
      sym_identifier,
      anon_sym_return,
  [1995] = 1,
    ACTIONS(34), 5,
      anon_sym_end,
      anon_sym_while,
      anon_sym_if,
      sym_identifier,
      anon_sym_return,
  [2003] = 1,
    ACTIONS(70), 5,
      anon_sym_end,
      anon_sym_while,
      anon_sym_if,
      sym_identifier,
      anon_sym_return,
  [2011] = 1,
    ACTIONS(193), 5,
      anon_sym_end,
      anon_sym_while,
      anon_sym_if,
      sym_identifier,
      anon_sym_return,
  [2019] = 1,
    ACTIONS(191), 5,
      anon_sym_end,
      anon_sym_while,
      anon_sym_if,
      sym_identifier,
      anon_sym_return,
  [2027] = 1,
    ACTIONS(197), 5,
      anon_sym_end,
      anon_sym_while,
      anon_sym_if,
      sym_identifier,
      anon_sym_return,
  [2035] = 1,
    ACTIONS(207), 5,
      anon_sym_var,
      anon_sym_while,
      anon_sym_if,
      sym_identifier,
      anon_sym_return,
  [2043] = 1,
    ACTIONS(187), 5,
      anon_sym_end,
      anon_sym_while,
      anon_sym_if,
      sym_identifier,
      anon_sym_return,
  [2051] = 3,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(209), 1,
      anon_sym_SEMI,
    STATE(93), 2,
      sym__brack_expr,
      aux_sym_array_type_repeat1,
  [2062] = 4,
    ACTIONS(211), 1,
      anon_sym_RPAREN,
    ACTIONS(213), 1,
      sym_identifier,
    STATE(106), 1,
      sym_parameter,
    STATE(128), 1,
      sym_parameters,
  [2075] = 3,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(215), 1,
      anon_sym_SEMI,
    STATE(4), 2,
      sym__brack_expr,
      aux_sym_array_type_repeat1,
  [2086] = 3,
    STATE(91), 1,
      sym_primitive_type,
    STATE(131), 1,
      sym_array_type,
    ACTIONS(217), 2,
      anon_sym_int,
      anon_sym_real,
  [2097] = 3,
    STATE(96), 1,
      sym_primitive_type,
    STATE(120), 1,
      sym_array_type,
    ACTIONS(217), 2,
      anon_sym_int,
      anon_sym_real,
  [2108] = 3,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(219), 1,
      anon_sym_SEMI,
    STATE(93), 2,
      sym__brack_expr,
      aux_sym_array_type_repeat1,
  [2119] = 1,
    ACTIONS(221), 3,
      ts_builtin_sym_end,
      anon_sym_func,
      anon_sym_var,
  [2125] = 1,
    ACTIONS(223), 3,
      ts_builtin_sym_end,
      anon_sym_func,
      anon_sym_var,
  [2131] = 1,
    ACTIONS(225), 3,
      ts_builtin_sym_end,
      anon_sym_func,
      anon_sym_var,
  [2137] = 3,
    ACTIONS(213), 1,
      sym_identifier,
    STATE(106), 1,
      sym_parameter,
    STATE(114), 1,
      sym_parameters,
  [2147] = 2,
    STATE(11), 1,
      sym_primitive_type,
    ACTIONS(227), 2,
      anon_sym_int,
      anon_sym_real,
  [2155] = 2,
    STATE(23), 1,
      sym_primitive_type,
    ACTIONS(217), 2,
      anon_sym_int,
      anon_sym_real,
  [2163] = 2,
    STATE(105), 1,
      sym_primitive_type,
    ACTIONS(217), 2,
      anon_sym_int,
      anon_sym_real,
  [2171] = 2,
    ACTIONS(229), 1,
      anon_sym_LPAREN,
    STATE(18), 1,
      sym_parameter_list,
  [2178] = 1,
    ACTIONS(231), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [2183] = 2,
    ACTIONS(233), 1,
      anon_sym_RPAREN,
    ACTIONS(235), 1,
      anon_sym_COMMA,
  [2190] = 2,
    ACTIONS(237), 1,
      anon_sym_end,
    ACTIONS(239), 1,
      anon_sym_else,
  [2197] = 2,
    ACTIONS(241), 1,
      anon_sym_end,
    ACTIONS(243), 1,
      anon_sym_else,
  [2204] = 1,
    ACTIONS(245), 1,
      anon_sym_RPAREN,
  [2208] = 1,
    ACTIONS(247), 1,
      sym_identifier,
  [2212] = 1,
    ACTIONS(249), 1,
      anon_sym_end,
  [2216] = 1,
    ACTIONS(251), 1,
      anon_sym_end,
  [2220] = 1,
    ACTIONS(253), 1,
      anon_sym_RPAREN,
  [2224] = 1,
    ACTIONS(255), 1,
      anon_sym_RPAREN,
  [2228] = 1,
    ACTIONS(257), 1,
      anon_sym_end,
  [2232] = 1,
    ACTIONS(259), 1,
      anon_sym_end,
  [2236] = 1,
    ACTIONS(205), 1,
      anon_sym_COLON_EQ,
  [2240] = 1,
    ACTIONS(261), 1,
      anon_sym_end,
  [2244] = 1,
    ACTIONS(263), 1,
      anon_sym_COLON,
  [2248] = 1,
    ACTIONS(219), 1,
      anon_sym_SEMI,
  [2252] = 1,
    ACTIONS(265), 1,
      anon_sym_RPAREN,
  [2256] = 1,
    ACTIONS(267), 1,
      anon_sym_end,
  [2260] = 1,
    ACTIONS(269), 1,
      ts_builtin_sym_end,
  [2264] = 1,
    ACTIONS(271), 1,
      sym_identifier,
  [2268] = 1,
    ACTIONS(273), 1,
      anon_sym_COLON,
  [2272] = 1,
    ACTIONS(201), 1,
      anon_sym_COLON_EQ,
  [2276] = 1,
    ACTIONS(275), 1,
      anon_sym_RPAREN,
  [2280] = 1,
    ACTIONS(277), 1,
      anon_sym_RPAREN,
  [2284] = 1,
    ACTIONS(279), 1,
      sym_identifier,
  [2288] = 1,
    ACTIONS(281), 1,
      anon_sym_COLON,
  [2292] = 1,
    ACTIONS(209), 1,
      anon_sym_SEMI,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 34,
  [SMALL_STATE(4)] = 66,
  [SMALL_STATE(5)] = 98,
  [SMALL_STATE(6)] = 124,
  [SMALL_STATE(7)] = 148,
  [SMALL_STATE(8)] = 176,
  [SMALL_STATE(9)] = 200,
  [SMALL_STATE(10)] = 224,
  [SMALL_STATE(11)] = 248,
  [SMALL_STATE(12)] = 272,
  [SMALL_STATE(13)] = 296,
  [SMALL_STATE(14)] = 322,
  [SMALL_STATE(15)] = 356,
  [SMALL_STATE(16)] = 388,
  [SMALL_STATE(17)] = 418,
  [SMALL_STATE(18)] = 442,
  [SMALL_STATE(19)] = 482,
  [SMALL_STATE(20)] = 519,
  [SMALL_STATE(21)] = 556,
  [SMALL_STATE(22)] = 593,
  [SMALL_STATE(23)] = 630,
  [SMALL_STATE(24)] = 667,
  [SMALL_STATE(25)] = 704,
  [SMALL_STATE(26)] = 741,
  [SMALL_STATE(27)] = 775,
  [SMALL_STATE(28)] = 811,
  [SMALL_STATE(29)] = 845,
  [SMALL_STATE(30)] = 878,
  [SMALL_STATE(31)] = 911,
  [SMALL_STATE(32)] = 942,
  [SMALL_STATE(33)] = 973,
  [SMALL_STATE(34)] = 1006,
  [SMALL_STATE(35)] = 1039,
  [SMALL_STATE(36)] = 1070,
  [SMALL_STATE(37)] = 1091,
  [SMALL_STATE(38)] = 1124,
  [SMALL_STATE(39)] = 1157,
  [SMALL_STATE(40)] = 1190,
  [SMALL_STATE(41)] = 1223,
  [SMALL_STATE(42)] = 1256,
  [SMALL_STATE(43)] = 1286,
  [SMALL_STATE(44)] = 1316,
  [SMALL_STATE(45)] = 1346,
  [SMALL_STATE(46)] = 1376,
  [SMALL_STATE(47)] = 1402,
  [SMALL_STATE(48)] = 1428,
  [SMALL_STATE(49)] = 1454,
  [SMALL_STATE(50)] = 1477,
  [SMALL_STATE(51)] = 1497,
  [SMALL_STATE(52)] = 1517,
  [SMALL_STATE(53)] = 1537,
  [SMALL_STATE(54)] = 1551,
  [SMALL_STATE(55)] = 1571,
  [SMALL_STATE(56)] = 1591,
  [SMALL_STATE(57)] = 1611,
  [SMALL_STATE(58)] = 1631,
  [SMALL_STATE(59)] = 1651,
  [SMALL_STATE(60)] = 1671,
  [SMALL_STATE(61)] = 1691,
  [SMALL_STATE(62)] = 1711,
  [SMALL_STATE(63)] = 1731,
  [SMALL_STATE(64)] = 1751,
  [SMALL_STATE(65)] = 1771,
  [SMALL_STATE(66)] = 1791,
  [SMALL_STATE(67)] = 1811,
  [SMALL_STATE(68)] = 1827,
  [SMALL_STATE(69)] = 1843,
  [SMALL_STATE(70)] = 1857,
  [SMALL_STATE(71)] = 1866,
  [SMALL_STATE(72)] = 1877,
  [SMALL_STATE(73)] = 1888,
  [SMALL_STATE(74)] = 1897,
  [SMALL_STATE(75)] = 1906,
  [SMALL_STATE(76)] = 1915,
  [SMALL_STATE(77)] = 1924,
  [SMALL_STATE(78)] = 1933,
  [SMALL_STATE(79)] = 1942,
  [SMALL_STATE(80)] = 1951,
  [SMALL_STATE(81)] = 1959,
  [SMALL_STATE(82)] = 1973,
  [SMALL_STATE(83)] = 1987,
  [SMALL_STATE(84)] = 1995,
  [SMALL_STATE(85)] = 2003,
  [SMALL_STATE(86)] = 2011,
  [SMALL_STATE(87)] = 2019,
  [SMALL_STATE(88)] = 2027,
  [SMALL_STATE(89)] = 2035,
  [SMALL_STATE(90)] = 2043,
  [SMALL_STATE(91)] = 2051,
  [SMALL_STATE(92)] = 2062,
  [SMALL_STATE(93)] = 2075,
  [SMALL_STATE(94)] = 2086,
  [SMALL_STATE(95)] = 2097,
  [SMALL_STATE(96)] = 2108,
  [SMALL_STATE(97)] = 2119,
  [SMALL_STATE(98)] = 2125,
  [SMALL_STATE(99)] = 2131,
  [SMALL_STATE(100)] = 2137,
  [SMALL_STATE(101)] = 2147,
  [SMALL_STATE(102)] = 2155,
  [SMALL_STATE(103)] = 2163,
  [SMALL_STATE(104)] = 2171,
  [SMALL_STATE(105)] = 2178,
  [SMALL_STATE(106)] = 2183,
  [SMALL_STATE(107)] = 2190,
  [SMALL_STATE(108)] = 2197,
  [SMALL_STATE(109)] = 2204,
  [SMALL_STATE(110)] = 2208,
  [SMALL_STATE(111)] = 2212,
  [SMALL_STATE(112)] = 2216,
  [SMALL_STATE(113)] = 2220,
  [SMALL_STATE(114)] = 2224,
  [SMALL_STATE(115)] = 2228,
  [SMALL_STATE(116)] = 2232,
  [SMALL_STATE(117)] = 2236,
  [SMALL_STATE(118)] = 2240,
  [SMALL_STATE(119)] = 2244,
  [SMALL_STATE(120)] = 2248,
  [SMALL_STATE(121)] = 2252,
  [SMALL_STATE(122)] = 2256,
  [SMALL_STATE(123)] = 2260,
  [SMALL_STATE(124)] = 2264,
  [SMALL_STATE(125)] = 2268,
  [SMALL_STATE(126)] = 2272,
  [SMALL_STATE(127)] = 2276,
  [SMALL_STATE(128)] = 2280,
  [SMALL_STATE(129)] = 2284,
  [SMALL_STATE(130)] = 2288,
  [SMALL_STATE(131)] = 2292,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expr, 1),
  [13] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expr, 1),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_access, 2),
  [19] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array_access, 2),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_type_repeat1, 2),
  [23] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_array_type_repeat1, 2),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_type_repeat1, 2), SHIFT_REPEAT(55),
  [28] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__brack_expr, 3),
  [30] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__brack_expr, 3),
  [32] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 3),
  [34] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 3),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, .production_id = 1),
  [38] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3, .production_id = 1),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1),
  [46] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primitive_type, 1),
  [50] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_primitive_type, 1),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 3),
  [54] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 3),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_cast, 3),
  [58] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_cast, 3),
  [60] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 4),
  [70] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 4),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [74] = {.entry = {.count = 1, .reusable = false}}, SHIFT(129),
  [76] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [78] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [80] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [82] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [84] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [86] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [88] = {.entry = {.count = 1, .reusable = false}}, SHIFT(81),
  [90] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 1),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 1),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_block_repeat2, 2),
  [114] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat2, 2), SHIFT_REPEAT(63),
  [117] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat2, 2), SHIFT_REPEAT(64),
  [120] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat2, 2), SHIFT_REPEAT(81),
  [123] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat2, 2), SHIFT_REPEAT(51),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [138] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat2, 2), SHIFT_REPEAT(66),
  [141] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat2, 2), SHIFT_REPEAT(52),
  [144] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat2, 2), SHIFT_REPEAT(82),
  [147] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat2, 2), SHIFT_REPEAT(65),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [166] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(110),
  [169] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(124),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [174] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(129),
  [177] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 2),
  [181] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameter_list, 2),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 3),
  [185] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameter_list, 3),
  [187] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if, 7),
  [189] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if, 5),
  [191] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_while, 5),
  [193] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment, 4),
  [195] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_return_statement, 3),
  [197] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 1),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [207] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_declaration, 5),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(130),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_type, 2),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declaration, 5),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 5),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 7),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [231] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 3),
  [233] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 1),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [255] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 3),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [269] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [275] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 3),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_e2(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
